const listaPistas=[
    'Saga de películas',
    'Saga de Películas',
    'Animal',
    'Juego de cartas',
    'Guía sobre algo',
    'Serie',
    'Serie',
    'Canción Queen',
    'Médico especializado en las enfermedades de la cabeza y del cuello',
    'Especialista en el uso del electroencefalograma',
    'Sólido limitado por seis paralelogramos, cuyas caras opuestas son iguales y paralelas',
    'De la fotosíntesis o que tiene relación con este proceso químico de las plantas',
    'Falta de ánimo o de disposición',
    'Descubrimiento afortunado e inesperado que se produce cuando se está buscando otra cosa distinta.',
    'Presenta propiedades intermedias entre los metales y los no metales',
    'Es un compuesto, que además del hidrógeno contiene un no metal de los grupos VIA o VIIA',
    'Punto donde se cortan las medianas de un triángulo',
    'Hueso curvo que forma parte de la rodilla',
    'Parálisis del brazo y de la pierna de un solo lado del cuerpo',
    'Sustancias químicas que matan insectos y otras plagas',
    'Grupo de islas más o menos próximas entre sí',
    'Ladera expuesta al viento',
    'Escurrimiento superficial que desemboca en el mar',
    'Relativo a los lugares donde existen condiciones de aridez',
    'Sinónimo de Glaciar',
    'Que esta situado al norte',
    'Sección baja o deprimida situada entre dos relieves mayores',
    'Depresiones pantanosas que abrigan una masa vegetacional característica',
    'Se refiere a las áreas donde las precipitaciones se concentran en invierno y donde el verano es seco',
    'Terreno  que hay entre cuencas vecinas',
    'Especies adaptadas a zonas de alta humedad',
    'Aparato que mide el número de revoluciones de un eje móvil o de una máquina.',
    'Motor auxiliar que sirve para amplificar un esfuerzo relativamente pequeño y conseguir un trabajo considerable',
    'Equivale al trabajo que hay que desarrollar para elevar verticalmente un peso de un kilogramo a una altura de un metro',

];


const listaPalabras=[
    'Star wars',   
    'Transformers' ,
    'Ornitorrinco', 
    'Poker', 
    'Instrucciones',
    'Breaking Bad', 
    'Friends',
    'Bohemian Rhapsody', 
    'Otorrinolaringologo',
    'Electroencefalografista',
    'Paralelepipedo',
    'Fotosinteticamente',
    'Desidia',
    'Serendipia',
    'Metaloide',
    'Hidroacido',
    'Baricentro',
    'Choquezuela',
    'Hemiplejia',
    'Plaguicidas',
    'Archipielago',
    'Barlovento',
    'Endorreica',
    'Xeromorfico',
    'Ventisquero',
    'Septentrional',
    'Portezuelo',
    'Ñadis',
    'Mesomorfica',
    'Interfluvio',
    'Higrofito',
    'Cuentarrevoluciones',
    'Servomotor',
    'Kilogrametro',

];




  
 